version: 6
daemon:
  log_level: info
  admin_group: wheel
  disable_clocks_cleanup: false
apply_settings_timer: 5
gpus:
  10DE:2B85-10DE:2057-0000:01:00.0:
    fan_control_enabled: false
    power_cap: 400.0
    min_core_clock: 180
    max_core_clock: 2763
    mem_clock_offsets:
      0: 2000
    gpu_vf_curve:
      0:
        voltage: 436
        clockspeed: 180
      1:
        voltage: 446
        clockspeed: 180
      2:
        voltage: 451
        clockspeed: 180
      3:
        voltage: 455
        clockspeed: 180
      4:
        voltage: 460
        clockspeed: 180
      5:
        voltage: 470
        clockspeed: 180
      6:
        voltage: 475
        clockspeed: 180
      7:
        voltage: 480
        clockspeed: 180
      8:
        voltage: 485
        clockspeed: 180
      9:
        voltage: 494
        clockspeed: 180
      10:
        voltage: 499
        clockspeed: 180
      11:
        voltage: 504
        clockspeed: 180
      12:
        voltage: 509
        clockspeed: 180
      13:
        voltage: 518
        clockspeed: 180
      14:
        voltage: 523
        clockspeed: 180
      15:
        voltage: 528
        clockspeed: 180
      16:
        voltage: 533
        clockspeed: 180
      17:
        voltage: 543
        clockspeed: 180
      18:
        voltage: 548
        clockspeed: 180
      19:
        voltage: 552
        clockspeed: 180
      20:
        voltage: 557
        clockspeed: 180
      21:
        voltage: 567
        clockspeed: 180
      22:
        voltage: 572
        clockspeed: 180
      23:
        voltage: 577
        clockspeed: 180
      24:
        voltage: 582
        clockspeed: 180
      25:
        voltage: 591
        clockspeed: 180
      26:
        voltage: 596
        clockspeed: 180
      27:
        voltage: 601
        clockspeed: 180
      28:
        voltage: 606
        clockspeed: 180
      29:
        voltage: 615
        clockspeed: 180
      30:
        voltage: 620
        clockspeed: 180
      31:
        voltage: 625
        clockspeed: 180
      32:
        voltage: 630
        clockspeed: 180
      33:
        voltage: 640
        clockspeed: 180
      34:
        voltage: 645
        clockspeed: 180
      35:
        voltage: 649
        clockspeed: 180
      36:
        voltage: 654
        clockspeed: 180
      37:
        voltage: 664
        clockspeed: 180
      38:
        voltage: 669
        clockspeed: 180
      39:
        voltage: 674
        clockspeed: 180
      40:
        voltage: 679
        clockspeed: 180
      41:
        voltage: 688
        clockspeed: 180
      42:
        voltage: 693
        clockspeed: 180
      43:
        voltage: 698
        clockspeed: 180
      44:
        voltage: 703
        clockspeed: 180
      45:
        voltage: 712
        clockspeed: 180
      46:
        voltage: 717
        clockspeed: 180
      47:
        voltage: 722
        clockspeed: 180
      48:
        voltage: 727
        clockspeed: 180
      49:
        voltage: 737
        clockspeed: 180
      50:
        voltage: 742
        clockspeed: 180
      51:
        voltage: 746
        clockspeed: 180
      52:
        voltage: 751
        clockspeed: 225
      53:
        voltage: 761
        clockspeed: 315
      54:
        voltage: 766
        clockspeed: 397
      55:
        voltage: 771
        clockspeed: 480
      56:
        voltage: 776
        clockspeed: 562
      57:
        voltage: 785
        clockspeed: 652
      58:
        voltage: 790
        clockspeed: 735
      59:
        voltage: 795
        clockspeed: 817
      60:
        voltage: 800
        clockspeed: 982
      61:
        voltage: 809
        clockspeed: 1372
      62:
        voltage: 814
        clockspeed: 1762
      63:
        voltage: 819
        clockspeed: 2152
      64:
        voltage: 824
        clockspeed: 2227
      65:
        voltage: 834
        clockspeed: 2317
      66:
        voltage: 839
        clockspeed: 2385
      67:
        voltage: 843
        clockspeed: 2482
      68:
        voltage: 848
        clockspeed: 2572
      69:
        voltage: 858
        clockspeed: 2655
      70:
        voltage: 863
        clockspeed: 2752
      71:
        voltage: 868
        clockspeed: 2827
      72:
        voltage: 873
        clockspeed: 2827
      73:
        voltage: 882
        clockspeed: 2827
      74:
        voltage: 887
        clockspeed: 2827
      75:
        voltage: 892
        clockspeed: 2827
      76:
        voltage: 897
        clockspeed: 2827
      77:
        voltage: 906
        clockspeed: 2827
      78:
        voltage: 911
        clockspeed: 2827
      79:
        voltage: 916
        clockspeed: 2827
      80:
        voltage: 921
        clockspeed: 2827
      81:
        voltage: 931
        clockspeed: 2827
      82:
        voltage: 936
        clockspeed: 2827
      83:
        voltage: 940
        clockspeed: 2827
      84:
        voltage: 945
        clockspeed: 2827
      85:
        voltage: 955
        clockspeed: 2827
      86:
        voltage: 960
        clockspeed: 2827
      87:
        voltage: 965
        clockspeed: 2827
      88:
        voltage: 970
        clockspeed: 2827
      89:
        voltage: 979
        clockspeed: 2827
      90:
        voltage: 984
        clockspeed: 2827
      91:
        voltage: 989
        clockspeed: 2827
      92:
        voltage: 994
        clockspeed: 2827
      93:
        voltage: 1003
        clockspeed: 2827
      94:
        voltage: 1008
        clockspeed: 2827
      95:
        voltage: 1013
        clockspeed: 2827
      96:
        voltage: 1018
        clockspeed: 2827
      97:
        voltage: 1028
        clockspeed: 2842
      98:
        voltage: 1033
        clockspeed: 2857
      99:
        voltage: 1037
        clockspeed: 2872
      100:
        voltage: 1042
        clockspeed: 2872
      101:
        voltage: 1052
        clockspeed: 2895
      102:
        voltage: 1057
        clockspeed: 2902
      103:
        voltage: 1062
        clockspeed: 2917
      104:
        voltage: 1067
        clockspeed: 2917
      105:
        voltage: 1076
        clockspeed: 2940
      106:
        voltage: 1081
        clockspeed: 2947
      107:
        voltage: 1086
        clockspeed: 2962
      108:
        voltage: 1091
        clockspeed: 2962
      109:
        voltage: 1100
        clockspeed: 2985
      110:
        voltage: 1105
        clockspeed: 2992
      111:
        voltage: 1110
        clockspeed: 2992
      112:
        voltage: 1115
        clockspeed: 3015
      113:
        voltage: 1125
        clockspeed: 3022
      114:
        voltage: 1130
        clockspeed: 3037
      115:
        voltage: 1134
        clockspeed: 3045
      116:
        voltage: 1139
        clockspeed: 3052
      117:
        voltage: 1149
        clockspeed: 3060
      118:
        voltage: 1154
        clockspeed: 3075
      119:
        voltage: 1159
        clockspeed: 3082
      120:
        voltage: 1164
        clockspeed: 3090
      121:
        voltage: 1173
        clockspeed: 3097
      122:
        voltage: 1178
        clockspeed: 3112
      123:
        voltage: 1183
        clockspeed: 3112
      124:
        voltage: 1188
        clockspeed: 3127
      125:
        voltage: 1197
        clockspeed: 3135
      126:
        voltage: 1202
        clockspeed: 3142
current_profile: null
auto_switch_profiles: false