import typing

from BaseClasses import ItemClassification, Region, Tutorial
from Options import Accessibility
from worlds.AutoWorld import WebWorld, World

from .Items import (
    MAX_CHECKS,
    MAX_ROOMS,
    SkeletonItem,
    event_code,
    item_table,
)
from .Locations import SkeletonLocation, location_table
from .Options import SkeletonOptions
from .Regions import create_regions
from .Rules import set_completion_rules, set_rules

client_version = 1

FILLER_ITEMS = ["Bone", "Skull Shard", "Ribbon"]


class SkeletonWeb(WebWorld):
    tutorials = [
        Tutorial(
            "Multiworld Setup Guide",
            "A guide to playing the Skeleton skeleton world in Archipelago.",
            "English",
            "setup_en.md",
            "setup/en",
            ["b"],
        )
    ]

    data = {
        "itemPoolGroupings": {
            "Keys": [f"Room {i} Key" for i in range(1, MAX_ROOMS + 1)] + ["Master Key"],
            "Filler": FILLER_ITEMS,
        },
    }


class SkeletonWorld(World):
    """
    Skeleton is a self-contained check-collecting game and a full-featured
    starting point for new Archipelago worlds.

    Explore the crypt: each room is locked behind its own key, every room
    holds a few checks, and the vault at the end holds the final check that
    completes the world. No ROM, no client, no external data — everything is
    generated by the world itself, so it works in any multiworld out of the
    box.
    """

    game = "Skeleton"
    options_dataclass = SkeletonOptions
    web = SkeletonWeb()

    item_name_to_id = {name: data.code for name, data in item_table.items()}
    location_name_to_id = {name: data.id for name, data in location_table.items()}

    def create_items(self) -> None:
        room_count = self.options.room_count.value
        checks_per_room = self.options.checks_per_room.value
        start_with_keys = self.options.start_with_keys.value

        # Room 1 is the bootstrap (always accessible); rooms 2..N each need a
        # key. Keys are only in the pool when the player does not start with
        # them; otherwise they are pushed as precollected items in
        # generate_early and filler takes their place in the pool.
        keys = [f"Room {i} Key" for i in range(2, room_count + 1)]
        keys.append("Master Key")

        items: typing.List[str] = []
        if not start_with_keys:
            items += keys

        # Item pool must match the location count minus the vault event.
        total_locations = room_count * checks_per_room + 1
        filler_count = total_locations - 1 - len(items)
        items += [FILLER_ITEMS[i % len(FILLER_ITEMS)] for i in range(filler_count)]

        self.multiworld.itempool += [self.create_item(name) for name in items]

    def create_regions(self) -> None:
        create_regions(self.multiworld, self.player)

        checks_per_room = self.options.checks_per_room.value
        room_count = self.options.room_count.value
        for i in range(1, room_count + 1):
            region = self.multiworld.get_region(f"Room {i}", self.player)
            region.locations += [
                self._create_location(f"Room {i} Check {j}", region)
                for j in range(1, checks_per_room + 1)
            ]

        # The vault location holds the completion event.
        vault = self.multiworld.get_region("Vault", self.player)
        vault_location = self._create_location("Vault", vault)
        vault.locations.append(vault_location)
        vault_location.place_locked_item(self.create_event("Final Check"))

    def set_rules(self) -> None:
        set_rules(self.multiworld, self.player)
        set_completion_rules(self.multiworld, self.player)

    def generate_early(self) -> None:
        # When starting with keys, hand them to the player up front (precollected)
        # rather than placing them in the pool. Room 1 needs no key (bootstrap).
        if self.options.start_with_keys.value:
            room_count = self.options.room_count.value
            for i in range(2, room_count + 1):
                self.multiworld.push_precollected(self.create_item(f"Room {i} Key"))
            self.multiworld.push_precollected(self.create_item("Master Key"))

    def set_world_info(self) -> None:
        room_count = self.options.room_count.value
        checks_per_room = self.options.checks_per_room.value
        self.multiworld.set_world_info(
            self.player,
            {
                "room_count": room_count,
                "checks_per_room": checks_per_room,
                "total_checks": room_count * checks_per_room + 1,
            },
        )

    def fill_slot_data(self) -> typing.Dict[str, typing.Any]:
        return {
            "client_version": client_version,
            "seed_name": self.multiworld.seed_name,
            "player_name": self.player_name,
            "player_id": self.player,
            "race": self.multiworld.is_race,
        }

    def create_item(self, name: str) -> SkeletonItem:
        data = item_table[name]
        return SkeletonItem(
            name,
            (
                ItemClassification.progression
                if data.progression
                else ItemClassification.filler
            ),
            data.code,
            self.player,
        )

    def create_event(self, name: str) -> SkeletonItem:
        return SkeletonItem(
            name, ItemClassification.progression, event_code, self.player
        )

    def _create_location(self, name: str, parent: Region) -> SkeletonLocation:
        data = location_table[name]
        return SkeletonLocation(self.player, name, data.id, parent)
