# Build the `dsh` package from the @deepseek-ai/dsh npm tarball
# (./tarball.nix) WITHOUT running npm.
#
# Why not the stock buildNpmPackage recipe: its `npm ci` step is
# memory-pathological on this tree — single-threaded, and its heap grows
# linearly with the V8 limit (OOM at 4 GiB after ~57 min, at 8 GiB after
# ~111 min). Instead the npm production closure is fetched as one
# fixed-output derivation per registry tarball (fetchurl), each verified
# against its own sha256 from deps-sha256.json, and the tree is installed
# by hand:
#
#   1. package-lock.json — the npm closure pin (placement + per-package
#      sha512 integrity), regenerated from the pinned tree by
#      update-deps.py. _meta.srcRev stamps the dsh source rev it was
#      generated from; a source move without a re-pin fails the eval below.
#   2. deps-sha256.json — url -> sha256 for every npm-closure tarball,
#      generated by update-deps.py, which downloads each tarball and
#      verifies its sha512 against the lock's integrity. (The pnpm side of
#      the old union file is gone: tarball.nix pins its store via
#      fetchPnpmDeps now.)
#   3. unpack-node-modules.py — expands each locked tarball into the
#      lockfile's node_modules placement, skipping dev-only and non-linux
#      entries (mirrors `npm ci --ignore-scripts` + `npm prune --omit=dev`).
#   4. installPhase runs each script package's preinstall/install/
#      postinstall (mirrors the `npm rebuild` that follows
#      `npm ci --ignore-scripts` in the stock hook). The script set is
#      discovered from the lockfile's hasInstallScript flags at evaluation
#      time, not pinned by hand.
#
# Re-pin flow: `just dsh-repin` moves the dsh input to the newest published
# release, then regenerates both data files (one command; no hashes to copy
# back on the npm side — the .nix files carry none; the pnpm side is the
# single fetchPnpmDeps hash in tarball.nix).
{ lib, bashInteractive, fetchurl, jq, makeWrapper, nodejs, pkgs, python3, runCommand, stdenv, versionCheckHook, versionCheckHomeHook, src, version, commit }:

let
  lock = builtins.fromJSON (builtins.readFile ./package-lock.json);
  sha256 = builtins.fromJSON (builtins.readFile ./deps-sha256.json);

  linuxApplicable = e:
    (! (lib.hasAttr "os" e) || lib.elem "linux" e.os)
    && (! (lib.hasAttr "cpu" e) || lib.elem "x64" e.cpu);

  # Production entries to install, keyed by their lockfile placement
  # (node_modules/... paths).
  entries =
    lib.filter (k:
      let e = lock.packages.${k};
      in k != "" && !(e.dev or false) && linuxApplicable e && e ? resolved
        && e ? integrity)
      (lib.attrNames lock.packages);

  # One fetchurl per unique tarball URL (fixed-output; the sha256 comes
  # from deps-sha256.json, which update-deps.py verified against the
  # lock's sha512 integrity).
  urls = lib.unique (lib.map (k: lock.packages.${k}.resolved) entries);
  tarballs = lib.listToAttrs (lib.map (u: {
    name = u;
    value = fetchurl {
      url = u;
      sha256 = sha256.${u}
        or (throw "deps-sha256.json is missing ${u} — run home/llm/dsh/update-deps.py");
    };
  }) urls);

  # Packages with install scripts (discovered from the lockfile, not
  # pinned by hand): their placement keys.
  scriptEntries =
    lib.filter (k: lock.packages.${k}.hasInstallScript or false) entries;

  # The node_modules tree, unpacked from the fetched tarballs. The entries
  # JSON is a store path (writeText): inlining it as an env var risks
  # exceeding MAX_ARG_STRLEN.
  unpackEntries = pkgs.writeText "dsh-${version}-unpack-entries.json"
    (lib.toJSON (lib.map (k: {
      key = k;
      tarball = "${tarballs.${lock.packages.${k}.resolved}}";
    }) entries));

  nodeModules = runCommand "dsh-${version}-node-modules"
    {
      nativeBuildInputs = [ python3 ];
    } ''
    OUT=$out \
    ENTRIES_FILE=${unpackEntries} \
    ${lib.getExe python3} ${./unpack-node-modules.py}
  '';
in
# The lock pin must come from exactly the pinned source tree: update-deps.py
# stamps package-lock.json with _meta.srcRev. A dsh source move without
# `just dsh-repin` would otherwise install a stale closure (missing or
# renamed production deps) with no build error, so fail loudly at eval time.
assert (lock._meta.srcRev or null) == commit
  || throw "stale home/llm/dsh/package-lock.json: the dsh source moved without a re-pin; run `just dsh-repin`";
stdenv.mkDerivation {
  pname = "dsh";
  inherit version;
  src = src;

  # nodejs in nativeBuildInputs so `node` is on PATH: with strictDeps, only
  # nativeBuildInputs (hostOffset=-1) get their bin/ on PATH, not buildInputs.
  # Also in buildInputs (matching the stock npm recipe) so it is a declared
  # dependency.
  nativeBuildInputs = [ makeWrapper jq nodejs ];
  buildInputs = [ nodejs ];

  strictDeps = true;
  # Stripping takes way too long with the amount of files in a Node.js tree.
  dontStrip = true;

  installPhase = ''
    runHook preInstall

    # node_modules: the unpacked tree (see file header for why we do not run
    # npm ci). The store path's top level IS node_modules/, so copy its
    # contents, not the path itself (which would nest node_modules/).
    cp -r ${nodeModules}/node_modules node_modules

    # Run the install scripts of the packages that declare them (mirrors the
    # `npm rebuild` that follows `npm ci --ignore-scripts` in the stock npm
    # hook). koffi compiles its prebuild (cc/make from stdenv); node-pty
    # verifies its bundled prebuild; the rest are no-ops/pure JS. The
    # placement keys are node_modules/... paths (nested-aware).
    for key in ${lib.concatStringsSep " " scriptEntries}; do
      dir="$key"
      for hook in preinstall install postinstall; do
        script=$(jq -r ".scripts.${"$"}{hook} // empty" "$dir/package.json")
        if [ -n "$script" ]; then
          echo "running $hook for $dir: $script"
          (cd "$dir" && eval "$script")
        fi
      done
    done

    patchShebangs node_modules

    # Install to $out (mirrors the stock npmInstallHook layout; dev entries
    # were already filtered at unpack).
    pkgOut="$out/lib/node_modules/@deepseek-ai/dsh"
    mkdir -p "$pkgOut"
    cp -r node_modules "$pkgOut/node_modules"
    for f in package.json lib README* LICENSE*; do
      [ -e "$f" ] && cp -r "$f" "$pkgOut/"
    done

    # The bin entry (mirrors the stock npmInstallHook, which symlinks each
    # package bin into $out/bin). postInstall removes it and replaces it with
    # a makeWrapper of the official node.
    mkdir -p "$out/bin"
    ln -s "$pkgOut/lib/bin.js" "$out/bin/dsh"

    # cp -r preserves the store's read-only modes (0444 files / 0555 dirs),
    # which blocks postInstall's in-place edits (patch/substituteInPlace need
    # to create temp files next to the targets). Make the tree writable.
    chmod -R u+w "$out"

    runHook postInstall
  '';

  postInstall = ''
    # /bin/bash does not exist on NixOS (issue #8068)
    substituteInPlace \
      $out/lib/node_modules/@deepseek-ai/dsh/node_modules/@deepseek-ai/dsh-terminal-bash/lib/index.js \
      --replace-fail '"/bin/bash"' '"${lib.getExe bashInteractive}"'

    # The account login shell is not always a usable terminal shell: service
    # and agent users commonly have nologin (and on NixOS its store path can be
    # garbage-collected), which made terminalEnvironment() report a path that
    # resolveExecutable() rejects with "is not an executable file", breaking
    # every default-shell terminal spawn. Only report the candidate when it is
    # an existing executable file; otherwise omit defaultShell so the consumer
    # (dsh-api-terminal-controller) picks the platform fallback (/bin/sh on
    # POSIX), per the documented terminalEnvironment contract.
    substituteInPlace \
      $out/lib/node_modules/@deepseek-ai/dsh/node_modules/@deepseek-ai/dsh-subprocess-local/lib/index.js \
      --replace-fail \
      'const defaultShell = platform === "windows" ? process.env.ComSpec || void 0 : process.env.SHELL || userInfo().shell || void 0;' \
      'let defaultShell = platform === "windows" ? process.env.ComSpec || void 0 : process.env.SHELL || userInfo().shell || void 0; if (defaultShell !== void 0) try { if (!(await stat(defaultShell)).isFile()) defaultShell = void 0; else await access(defaultShell, constants.X_OK); } catch { defaultShell = void 0; }'

    rm $out/bin/dsh
    makeWrapper ${lib.getExe nodejs} $out/bin/dsh \
      --argv0 dsh \
      --add-flags "--expose-internals" \
      --add-flags "$out/lib/node_modules/@deepseek-ai/dsh/lib/bin.js"
  '';

  doInstallCheck = true;
  nativeInstallCheckInputs = [
    versionCheckHook
    versionCheckHomeHook
  ];
  versionCheckProgramArg = "--version";

  meta = {
    description = "Open-source agent harness developed by DeepSeek AI";
    homepage = "https://github.com/deepseek-ai/deepseek-harness";
    changelog = "https://github.com/deepseek-ai/deepseek-harness/releases";
    downloadPage = "https://www.npmjs.org/package/@deepseek-ai/dsh";
    license = lib.licenses.mit;
    sourceProvenance = with lib.sourceTypes; [
      fromSource
    ];
    mainProgram = "dsh";
    platforms = lib.platforms.all;
  };
}
