{ pkgs, inputs, ... }:

let
  # The local services CA generated by hosts/desktop/local-ca.nix. Re-imported
  # here (same deterministic store path caddy.nix serves) so we can hand it to
  # Firefox directly.
  localServicesCA =
    (import ../../hosts/desktop/local-ca.nix {
      inherit pkgs;
      lib = pkgs.lib;
    }).ca;

  # Tether's Firefox integration: the OTP-autofill add-on (.xpi) and the
  # native-messaging host it talks to. Both are built by the tether flake.
  tetherPkgs = inputs.tether.packages.${pkgs.system};
in
{
  programs.firefox = {
    enable = true;

    # Firefox ignores the OS system store and ImportEnterpriseRoots is
    # unreliable on NixOS (no p11-kit trust module), so install the CA directly
    # into Firefox's NSS store; the trust persists across rebuilds.
    policies = {
      Certificates.Install = [ "${localServicesCA}/ca.crt" ];
    };

    profiles.main = {
      extensions = {
        packages =
          (import ./addons.nix { inherit pkgs; })
          ++ [ tetherPkgs."firefox-extension" ];

        settings =
          import ./tree_style_tab.nix { inherit pkgs; };
      };

      settings =
        import ./settings.nix;

      userChrome =
        builtins.readFile ./userChrome.css;

      bookmarks = {
        force = true;
        settings = [
          {
            name = "Subreddit shortcut";
            keyword = "r";
            url = "https://old.reddit.com/r/%s";
          }
        ];
      };
    };
  };

  # The extension reaches tetherd over native messaging. The host manifest is
  # linked as a single file rather than via programs.firefox.nativeMessagingHosts
  # (which symlinks the entire ~/.mozilla/native-messaging-hosts directory): that
  # directory is managed manually here — it also holds the Bitwarden manifest —
  # and a whole-directory symlink would abort the switch. Linking one file leaves
  # the directory (and the other manifests) untouched.
  home.file.".mozilla/native-messaging-hosts/com.tether.extension.json" = {
    source =
      "${tetherPkgs."native-host"}/lib/mozilla/native-messaging-hosts/com.tether.extension.json";
  };
}
