{ pkgs, inputs, ... }:

let
  # The local services CA generated by hosts/desktop/local-ca.nix. Re-imported
  # here (same deterministic store path caddy.nix serves) so we can hand it to
  # Firefox directly.
  localServicesCA =
    (import ../../hosts/desktop/local-ca.nix {
      inherit pkgs;
      lib = pkgs.lib;
    }).ca;

  # Tether's Firefox integration: the OTP-autofill add-on and the
  # native-messaging host it talks to. The add-on is the upstream bundle
  # repacked into the NUR xpi layout (see flake.nix); the host manifest comes
  # from the upstream package.
  tetherPkg = inputs.tether.packages.${pkgs.system}.default;
  tetherFirefoxXpi = inputs.self.packages.${pkgs.system}."tether-firefox-extension";
in
{
  programs.firefox = {
    enable = true;

    # The extension reaches tetherd over native messaging. home-manager
    # symlinks each host manifest into ~/.mozilla/native-messaging-hosts/
    # individually, so the manually managed Bitwarden manifest in that
    # directory is untouched.
    nativeMessagingHosts = [ tetherPkg ];

    # Firefox ignores the OS system store and ImportEnterpriseRoots is
    # unreliable on NixOS (no p11-kit trust module), so install the CA directly
    # into Firefox's NSS store; the trust persists across rebuilds.
    policies = {
      Certificates.Install = [ "${localServicesCA}/ca.crt" ];
    };

    profiles.main = {
      extensions = {
        packages =
          (import ./addons.nix { inherit pkgs; })
          ++ [ tetherFirefoxXpi ];

        settings =
          import ./tree_style_tab.nix { inherit pkgs; };
      };

      settings =
        import ./settings.nix;

      userChrome =
        builtins.readFile ./userChrome.css;

      bookmarks = {
        force = true;
        settings = [
          {
            name = "Subreddit shortcut";
            keyword = "r";
            url = "https://old.reddit.com/r/%s";
          }
        ];
      };
    };
  };
}
