{ pkgs, ... }:

let
  # The local services CA generated by hosts/desktop/local-ca.nix. Re-imported
  # here (same deterministic store path caddy.nix serves) so we can hand it to
  # Firefox directly.
  localServicesCA =
    (import ../../hosts/desktop/local-ca.nix {
      inherit pkgs;
      lib = pkgs.lib;
    }).ca;
in
{
  programs.firefox = {
    enable = true;

    # Install the local services CA into Firefox's own NSS trust store.
    # Firefox ignores the OS system store by default, and ImportEnterpriseRoots
    # is unreliable on NixOS (no p11-kit trust module), so without this it
    # reports SEC_ERROR_UNKNOWN_ISSUER for the *.local services. The CA
    # derivation's output path is stable across rebuilds (path-addressed; only
    # rebuilt on first use or after GC), so this trust persists. Takes effect
    # on the next Firefox restart.
    policies = {
      Certificates.Install = [ "${localServicesCA}/ca.crt" ];
    };

    profiles.main = {
      extensions = {
        packages =
          import ./addons.nix { inherit pkgs; };

        settings =
          import ./tree_style_tab.nix { inherit pkgs; };
      };

      settings =
        import ./settings.nix;

      userChrome =
        builtins.readFile ./userChrome.css;

      bookmarks = {
        force = true;
        settings = [
          {
            name = "Subreddit shortcut";
            keyword = "r";
            url = "https://old.reddit.com/r/%s";
          }
        ];
      };
    };
  };
}
